---
apoVersion: apps/vi
kind: Deployment
metadata:
  name: result-app-deployment
  labels:
    author: francis
    name: result-app-deployment
spec:
  replicas: 2
  selector:
    matchlabels:
      name: result-app-deployment
  template:
    metadata:
      name: result-app-pod
      labels:
        name: result-app-deployment
  spec:
    containers:
      - name: result-app
        image: dockersamples/examplevotingapp_result
...